package repositories

import (
	"post_service/internal/requests"
	"post_service/internal/responses"
)

type PostRepository interface {
	Create(requests.PostWithAuthRequest) responses.PostResponse
	Update(requests.PostWithAuthRequest) responses.PostResponse
	GetByIdIfUserCanView(requests.RequestWithAuthAndId) responses.PostResponse
	DeleteById(requests.RequestWithAuthAndId) responses.PostResponse
	GetPostsByTagWithPagination(requests.GetPostByTagWithPaginationRequest) responses.ListPostWithPaginationResponse
	GetPostsWithPagination(requests.GetPostWithPaginationInterface) responses.ListPostWithPaginationResponse
	GetPostByMentionWithPagination(requests.GetPostByMentionWithPaginationRequest) responses.ListPostWithPaginationResponse
	GetPostsForUserProfile(requests.GetPostForUserWithPagination) responses.ListPostWithPaginationResponse
}
